//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod t_department;
pub mod t_employee;
pub mod t_menu;
pub mod t_operate_log;
pub mod t_position;
pub mod t_role;
pub mod t_role_employee;
pub mod t_role_menu;
