//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::t_department::Entity as TDepartment;
pub use super::t_employee::Entity as TEmployee;
pub use super::t_menu::Entity as TMenu;
pub use super::t_operate_log::Entity as TOperateLog;
pub use super::t_position::Entity as TPosition;
pub use super::t_role::Entity as TRole;
pub use super::t_role_employee::Entity as TRoleEmployee;
pub use super::t_role_menu::Entity as TRoleMenu;
