//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_department")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub department_id: i64,
    pub name: String,
    pub manager_id: Option<i64>,
    pub parent_id: i64,
    pub sort: i32,
    pub update_time: i64,
    pub create_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
