//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_employee")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub employee_id: i64,
    pub login_name: String,
    pub login_pwd: String,
    pub realname: String,
    pub avatar: Option<String>,
    pub gender: i8,
    pub phone: Option<String>,
    pub department_id: i32,
    pub position_id: Option<i64>,
    pub email: Option<String>,
    pub disabled_flag: u8,
    pub deleted_flag: u8,
    pub administrator_flag: i8,
    pub login_token: String,
    pub login_at: i64,
    pub remark: Option<String>,
    pub update_time: i64,
    pub create_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
