//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_employee")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub employee_id: i64,
    pub login_name: String,
    pub login_pwd: String,
    pub realname: String,
    pub avatar: String,
    pub gender: u8,
    pub phone: String,
    pub department_id: i64,
    pub position_id: i64,
    pub email: String,
    pub disabled_flag: u8,
    pub deleted_flag: u8,
    pub administrator_flag: i8,
    pub login_token: String,
    pub login_at: i64,
    pub remark: String,
    pub update_time: i64,
    pub create_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
