//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub menu_id: i64,
    pub menu_name: String,
    pub menu_type: i32,
    pub parent_id: i64,
    pub sort: Option<i32>,
    pub path: Option<String>,
    pub component: Option<String>,
    pub perms_type: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_perms: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub web_perms: Option<String>,
    pub icon: Option<String>,
    pub context_menu_id: Option<i64>,
    pub frame_flag: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub frame_url: Option<String>,
    pub cache_flag: i8,
    pub visible_flag: i8,
    pub disabled_flag: i8,
    pub deleted_flag: i8,
    pub create_user_id: i64,
    pub create_time: i64,
    pub update_user_id: Option<i64>,
    pub update_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
