//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_operate_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub operate_log_id: i64,
    pub operate_user_id: i64,
    pub operate_user_type: i32,
    pub operate_user_name: String,
    pub module: Option<String>,
    pub content: Option<String>,
    pub url: Option<String>,
    pub method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub param: Option<String>,
    pub ip: Option<String>,
    pub ip_region: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub success_flag: Option<i8>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub fail_reason: Option<String>,
    pub update_time: i64,
    pub create_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
