//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_position")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub position_id: i64,
    pub position_name: String,
    pub level: String,
    pub sort: i64,
    pub remark: String,
    pub deleted_flag: i64,
    pub create_time: i64,
    pub update_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
