//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub role_id: i64,
    pub role_name: String,
    #[sea_orm(unique)]
    pub role_code: Option<String>,
    pub remark: Option<String>,
    pub update_time: i64,
    pub create_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
